[package]
name = "emerald-city"
version = "0.1.0"

authors = [
    "Omer <omer@kzencorp.com>"
]
description = "WASM/HW-friendly lightweight client application for threshold ECDSA"
homepage = "https://github.com/KZen-networks"
repository = "https://github.com/KZen-networks/emerald-city"
license = "GPL-3.0-or-later"


[lib]
crate-type = ["staticlib", "lib"]


[dependencies]
rand = { version="0.6.5", features = ["wasm-bindgen"] } #, features = ["stdweb"]
# rand = { git = "https://github.com/rust-lang-nursery/rand" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"


num-bigint = {version = "0.2.2" , features = ["serde","rand"]}
num-integer = "0.1"
num-traits = "0.2.6"


bit-vec = "0.5"
cryptoxide = "0.1.1"
zeroize = "0.5.2"

libsecp256k1 = "0.2.2"

# [target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.2"
# { git = 'https://github.com/rustwasm/wasm-bindgen' }

# [patch.crates-io]
# rand = { version="*", git = "https://github.com/rust-lang-nursery/rand" }
# https://github.com/rust-lang/crates.io-index